### **D2APR: Aprendizado de M√°quina e Reconhecimento de Padr√µes** (IFSP, Campinas) <br/>
**Prof**: Samuel Martins (Samuka) <br/>

<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>. <br/><br/>

#### Custom CSS style

In [1]:
%%html
<style>
.dashed-box {
    border: 1px dashed black !important;
#    font-size: var(--jp-content-font-size1) !important;
}

.dashed-box table {

}

.dashed-box tr {
    background-color: white !important;
}
        
.alt-tab {
    background-color: black;
    color: #ffc351;
    padding: 4px;
    font-size: 1em;
    font-weight: bold;
    font-family: monospace;
}
// add your CSS styling here
</style>

<span style='font-size: 2.5em'><b>Cardiovascular Disease üíî</b></span><br/>
<span style='font-size: 1.5em'>Predict cardiovascular diseases</span>

<span style="background-color: #ffc351; padding: 4px; font-size: 1em;"><b>Sprint #?? - Draft</b></span>

<img src="./imgs/cardio.png" width=300/>

---

## Before starting this notebook
This jupyter notebook is designed for **experimental and teaching purposes**. <br/>
Although it is (relatively) well organized, it aims at solving the _target problem_ by evaluating (and documenting) _different solutions_ for somes steps of the **machine learning pipeline** ‚Äî see the [***Machine Learning Project Checklist by xavecoding***](https://github.com/xavecoding/IFSP-CMP-D2APR-2021.2/blob/main/cheat-sheets/machine-learning-project-checklist_by_xavecoding.pdf). <br/>
We tried to make this notebook as literally a _notebook_. Thus, it contains notes, drafts, comments, etc.<br/>

For teaching purposes, some parts of the notebook may be _overcommented_. Moreover, to simulate a real development scenario, we will divide our solution and experiments into **"sprints"** in which each sprint has some goals (e.g., perform _feature selection_, train more ML models, ...). <br/>
The **sprint goal** will be stated at the beginning of the notebook.

A ***final notebook*** (or any other kind of presentation) that compiles and summarizes all sprints ‚Äî the target problem, solutions, and findings ‚Äî should be created later.

#### Conventions

<ul>
    <li>üí° indicates a tip. </li>
    <li> ‚ö†Ô∏è indicates a warning message. </li>
    <li><span class='alt-tab'>alt tab</span> indicates and an extra content (<i>e.g.</i>, slides) to explain a given concept.</li>
</ul>

---

## üéØ Sprint Goals
- Evaluate on the training set:
  + Linear SVM
  + SVM Polynomial Kernel
  + SVM RBF Kernel
---

### 0. Imports and default settings for plotting

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")

params = {'legend.fontsize': 'x-large',
          'figure.figsize': (15, 5),
         'axes.labelsize': 'x-large',
         'axes.titlesize':'x-large',
         'xtick.labelsize':'x-large',
         'ytick.labelsize':'x-large'}
plt.rcParams.update(params)

### üèãÔ∏è‚Äç‚ôÄÔ∏è 6. Train ML Algorithms

#### [PyCaret](https://pycaret.org/guide/)
Installation - https://pycaret.readthedocs.io/en/latest/installation.html <br/>
Toy example for Binary Classification - https://github.com/pycaret/pycaret/blob/master/tutorials/Binary%20Classification%20Tutorial%20Level%20Beginner%20-%20%20CLF101.ipynb

In [3]:
cardio_train = pd.read_csv('./datasets/cardio_clean_train.csv')

In [4]:
cardio_train

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,21875,2,171,74.0,120,80,1,1,0,0,0,1
1,15302,1,162,66.0,110,80,1,1,0,0,1,0
2,18079,1,166,69.0,120,80,1,2,0,0,1,0
3,21680,1,169,65.0,120,80,1,1,0,0,0,1
4,14368,1,155,80.0,120,80,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
54715,19137,2,178,99.0,150,100,1,1,0,0,1,1
54716,19649,1,170,65.0,110,70,1,1,0,0,0,0
54717,18056,1,165,67.0,120,80,1,1,0,0,1,0
54718,20321,1,161,64.0,150,90,2,1,0,0,1,1
54719,19033,2,173,60.0,120,80,1,1,1,0,1,0

In [5]:
from pycaret.classification import *
exp_clf101 = setup(data=cardio_train,
                   target='cardio',
                   train_size=0.8,
                   session_id=123,
                   normalize=True,
                   numeric_imputation='median',
                   normalize_method='robust',
                   fold=5)

In [6]:
best_model = compare_models()